Source/MXHDL_DiMuonNoi/Controllers/PlaceController.cs
using DTOLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MXHDL_DiMuonNoi.Controllers
{
    public class PlaceController : Controller
    {
        //
        // GET: /Place/

        BUSLibrary.RetrievedPost busRes2 = new BUSLibrary.RetrievedPost();
        BUSLibrary.Account busAccount = new BUSLibrary.Account();
        BUSLibrary.RatingInfo busRating = new BUSLibrary.RatingInfo();
        public ActionResult Index(String id)
        {
            String email = "";
            var cookie = Request.Cookies["Email"];

            if (cookie == null)
            {
                return View("Login");
            }

            email = cookie.Value;
            DTOLibrary.THONGTIN accInfos = busAccount.getAccountInfos(email);

            ViewBag.AccInfos = accInfos;
            ViewBag.AvgScore = busRating.getAvgScore(id);
            DTOLibrary.RetrievedPost post = busRes2.getSystemPostById(id);
            return View(post);
        }
        [HttpPost]
        public ActionResult Rate(RatingInfo info)
        {
            String email = "";
            var cookie = Request.Cookies["Email"];

            if (cookie == null)
            {
                return View("Login");
            }

            email = cookie.Value;

            info.email = email;
            info.time = DateTime.Now;
            busRating.ratePlace(info);
            return Redirect("Index/" + info.placeId);
        }
    }
}

Source/MXHDL_DiMuonNoi/Views/Place/Index.cshtml
@model DTOLibrary.RetrievedPost
@{
    DTOLibrary.THONGTIN accInfos = ViewBag.AccInfos;
    ViewBag.Title = accInfos.Ten + " - DiMuonNoi";
    double avgScore = ViewBag.AvgScore;
}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Nguyễn Cường Thịnh - DiMuonNoi</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="@Url.Content("~/Content/960_24_col.css")" 
                   rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/style.css")" 
                   rel="stylesheet" type="text/css" />
</head>
<body>

    <!-- HEADER & NAVIGATION -->
    <div class="container_24">
        <!-- popup box for uploading new avatar/cover photo -->
        <div id="box-popup-changeavt" class="grid_18 box-popup">
            <div class="box-titlebar" onclick="$('#box-popup-changeavt').toggle();">[X] Đóng</div>
            <div class="box-content">Upload avatar mới:</div>
            @using (@Html.BeginForm("ChangeAvatar", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {                 
                <input type="file" value="Chọn hình" name="file" />
                <input type="submit" value="OK" />                                  
            }
        </div>
        <div id="box-popup-changecvr" class="grid_18 box-popup">
            <div class="box-titlebar" onclick="$('#box-popup-changecvr').toggle();">[X] Đóng</div>
            <div class="box-content">Upload cover mới:</div>
            @using (@Html.BeginForm("ChangeCover", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {                 
                <input type="file" value="Chọn hình" name="file" />
                <input type="submit" value="OK" />                                  
            }
        </div>
        <!-- left column (logo, menu) -->
        <div class="left-col">
            <!-- logo -->
            <div class="logo"></div>
            <!-- menu -->
            <div class="menu">

                @Html.ActionLink("Trang cá nhân", "Home", "Account", new object { }, new { @class = "item" })
                <a class="item" href="javascript:alert('Chức năng đang xây dựng');">Sửa thông tin</a>
                <a class="item" href="javascript:alert('Chức năng đang xây dựng');">Đăng xuất</a>

            </div>
        </div>

        <!-- column column (advertisements) -->
        <div class="right-col">
            <div class="grid_4 promotions">Khuyến mãi</div>
            <!-- Ads -->
            <div class="grid_4 ad-box">
                <div class="ad-box-content">
                    <img src="../../images/company/newworldhotel/albums/newroom/2.jpg" /><br />
                    New Rooms!<br />
                    at <a class="link" href="doanhnghiep.html">New World's Hotel</a>
                </div>
            </div>
            <div class="grid_4 ad-box">
                <div class="ad-box-content">
                    <img src="../../../Content/images/company/newworldhotel/photos/pool.jpg" /><br />
                    Da Pool~!<br />
                    New World's Hotel
                </div>
            </div>
            <div class="grid_4 ad-box">
                <div class="ad-box-content">
                    <img src="../../../Content/images/company/newworldhotel/albums/newroom/1.jpg" /><br />
                    New Promotion
                </div>
            </div>
            <div class="grid_4 ad-box">
                <div class="ad-box-content">
                    <img src="../../../Content/images/company/newworldhotel/albums/newroom/3.jpg" /><br />
                    Old Promotion
                </div>
            </div>
        </div>
        <div class="wrapper" style="border-top: 0;">
            <!-- header -->
            <div class="header">
                <!-- user photo -->
                @* <div class="push_1 grid_4 user-photo" onMouseOver="$('#btn_changeAvatar').toggle();" onMouseOut="$('#btn_changeAvatar').toggle();">
			<div class="user-box-border">
				<img src="@Url.Content("~/" + accInfos.AnhDaiDien)"/>
			</div>
			<div id="btn_changeAvatar" class="btn-popup-changeavt" onClick="$('#box-popup-changeavt').toggle();">
             @using (@Html.BeginForm("ChangeAvatar", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }))
             {
                 ViewBag.curHompageInfos = Model;
                 ViewBag.blah = "asdasdasdsad";
                <input type="file" value="Đổi hình đại diện" name="file"/>
                 <input type="submit" value="OK"/>
             }
            </div>			
			</div>    *@
                <!-- user photo -->
                <div class="push_1 grid_4 user-photo" onmouseover="$('#btn_changeAvatar').toggle();" onmouseout="$('#btn_changeAvatar').toggle();">
                    <div class="user-box-border">
                        <img src="@Url.Content("~/" + accInfos.AnhDaiDien)"/>
                    </div>
                    <div id="btn_changeAvatar" class="btn-popup-changeavt" onclick="$('#box-popup-changeavt').toggle();">Đổi hình đại diện</div>
                </div>



                <!-- user info -->
                <div class="push_1 grid_18 user-info">
                    <div class="user-box-border">
                        <table class="user-info-text">
                            <tr>
                                <td valign="top" align="left" width="400px">
                                    <div class="user-name">@accInfos.Ten</div>
                                    <div class="user-job">@accInfos.NgheNghiep</div>
                                </td>
                                <td valign="top" align="right">Hiện đang ở @accInfos.DiaChi</td>
                            </tr>
                            <tr>
                                <td valign="bottom" align="left">Đã đặt chân đến 5 miền đất nước.</td>
                                <td valign="bottom" align="right">"@accInfos.TamTrang"</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <!-- search box -->
            <div class="search-box">
                <div class="push_14 grid_9 search-content">
                    <form method="post" action="timkiem.html" onsubmit="alert('Demo: tìm kiếm địa điểm \'Tây Ninh\'');">
                        <input type="text" class="search-input" value="Điểm đến tiếp theo của bạn?.." onfocus="if(this.value=='Điểm đến tiếp theo của bạn?..')this.value='';" onblur="if(this.value=='')this.value='Điểm đến tiếp theo của bạn?..';" />
                        <div class="search-icon">
                            <input type="submit" class="search-button" value="" />
                        </div>
                    </form>
                </div>
            </div>
            <!-- cover -->
            <div class="clear"></div>
            <div onmouseover="$('#btn_changeCover').toggle();" onmouseout="$('#btn_changeCover').toggle();">
                <div class="grid_24 cover">
                    <img src="@Url.Content("~/" + accInfos.AnhBia)" />
                </div>
                <div id="btn_changeCover" class="btn-popup-changecvr" onclick="$('#box-popup-changecvr').toggle();">Đổi hình nền</div>
            </div>

            <div class="clear"></div>
            <!-- navigator -->
            <div class="nav" style="padding: 10px 5px 0px 0px">
                <!-- status form -->
                <div class="grid_8 statusForm">
                    <form method="post" name="statusForm">
                        <div class="txt-status">
                            <textarea class="txtStatus">Nhập thông điệp của bạn</textarea></div>
                        <div class="btn-photo">
                            <input type="button" class="btnPhoto" value="+ Thêm ảnh" /></div>
                        <div class="btn-submit">
                            <input type="button" class="btnSubmit" value="Gửi" /></div>
                    </form>
                </div>
                <!-- nav buttons -->
                <div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');">
                    <img src="../../../Content/images/icon/canhan/hinhanh.png" /></a></div>
                <div class="grid_3 nav-button"><a href="/Post/New">
                    <img src="../../../Content/images/icon/canhan/baiviet.png" /></a></div>
                <div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');">
                    <img src="../../../Content/images/icon/canhan/chuyendi.png" /></a></div>
                <div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');">
                    <img src="../../../Content/images/icon/canhan/yeuthich.png" /></a></div>
                <div class="grid_3 nav-button"><a href="/Friend/Index">
                    <img src="../../../Content/images/icon/canhan/banbe.png" /></a></div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    @if (Model != null)
    {
    <!-- SINGLE POST -->

    <div class="container_24 user-post-item">
        <div class="wrapper">
            <table>
                <tr>
                    <td valign="top" align="left">
                        <div class="album-title">@Model.Title<span class="album-date">@Model.Time</span></div>
                        <div class="album-detail">@Model.Content</div>
                    </td>
                    <td>
                        Điểm: @avgScore
                    </td>
                    <td>
                        @using (Html.BeginForm("Rate", "Place", FormMethod.Post))
                        {
                            <select name="star" id="star">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                            <input id="placeId" name="placeId" type="hidden" value="@Model.Id"/>
                            <input type="submit" value="Rate" />
                        }
                    </td>
                </tr>
                
                <!-- COMMENT BOX -->
                <tr>
                    <td valign="top" align="left" colspan="2">
                        
                        
                        <!-- COMMENT FORM -->

                        <div class="form-comment">
                            <table>
                                <tr>
                                    <td valign="top" align="left" width="50px" height="50px">
                                        <div class="comment-user-photo">
                                            <img src="@Url.Content("~/" + accInfos.AnhDaiDien)" width="100%" height="100%"/>
                                        </div>
                                    </td>
                                    <td valign="top" align="left">
                                        <div class="input-wrapper">
                                            <div class="txt-comment">
                                                <textarea rows="2" cols="70" class="txt-comment"></textarea>
                                            </div>
                                        </div>
                                        <div class="input-wrapper">
                                            <input type="submit" class="sbm-comment" value="Gửi" />
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </td>
                </tr>
                <!-- end COMMENT BOX -->


            </table>
        </div>
    </div>
    <!-- END SINGLE POST -->
    }
    else
    {
        <div class="container_24 user-post-item">
        <div class="wrapper">
        <div class="album-title">Không tìm thấy địa điểm!</div>
            </div>
            </div>

    }
    <div class="clear"></div>

    <div class="container_24 user-post-item">
        <div class="footer">
            <hr />
            <div class="footer-copyright">
                Bản quyền thuộc DiMuonNoi
            </div>
            <div class="footer-links">
                <a href="#">Giới thiệu</a>
                <a href="#">Trợ giúp</a>
                <a href="#">Quy định</a>
                <a href="#">Báo cáo</a>
            </div>
        </div>
    </div>
</body>
</html>