Source/MXHDL_DiMuonNoi/Controllers/BusinessUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MXHDL_DiMuonNoi.Controllers
{
    public class BusinessUserController : Controller
    {
        //
        // GET: /BusinessUser/
        BUSLibrary.BusinessUser busUser = new BUSLibrary.BusinessUser();

        public ActionResult ChangeInfo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangeInfo(DTOLibrary.THONGTINDOANHNGHIEP info)
        {
            String email = "";
            var cookie = Request.Cookies["Email"];

            if (cookie == null)
            {
                return View("Login");
            }
            email = cookie.Value;

            if (!busUser.changeUserInfo(email, info))
            {
                ViewBag.changeInfo = false;
            }
            else
            {
                ViewBag.changeInfo = true;
                return RedirectToAction("Home", "Account");
            }
            return View("ChangeInfo");
        }


    }
}

Source/MXHDL_DiMuonNoi/Views/BusinessUser/Advertisements.cshtml
@{
    Layout = "~/Views/Shared/_EmptyLayout.cshtml";
    bool isOwner = false;
    if (ViewBag.isOwner != null)
    {
        isOwner = ViewBag.isOwner;
    }
}

<div class="right-col">
    <div class="grid_4 promotions">
        Khuyến mãi</div>
    <!-- Ads -->
    <div class="grid_4 ad-box">
        <div class="ad-box-content">
            <img src="../../images/company/newworldhotel/albums/newroom/2.jpg" /><br />
            New Rooms!<br />
            at <a class="link" href="doanhnghiep.html">New World's Hotel</a>
        </div>
    </div>
    <div class="grid_4 ad-box">
        <div class="ad-box-content">
            <img src="../../../Content/images/company/newworldhotel/photos/pool.jpg" /><br />
            Da Pool~!<br />
            New World's Hotel
        </div>
    </div>
    <div class="grid_4 ad-box">
        <div class="ad-box-content">
            <img src="../../../Content/images/company/newworldhotel/albums/newroom/1.jpg" /><br />
            New Promotion
        </div>
    </div>
    <div class="grid_4 ad-box">
        <div class="ad-box-content">
            <img src="../../../Content/images/company/newworldhotel/albums/newroom/3.jpg" /><br />
            Old Promotion
        </div>
    </div>
</div>
        

Source/MXHDL_DiMuonNoi/Views/BusinessUser/ChangeInfo.cshtml
<!-- SINGLE POST : ALBUM -->
@model DTOLibrary.THONGTINDOANHNGHIEP
<div class="container_24 user-post-item">
@{    
     
    DTOLibrary.THONGTIN curUserInfo = ViewBag.curUser;
    String email = Request.Cookies["Email"].Value;
}
<div class="wrapper" >
                       <!--<form action="/Account/Register" name="f_register" method="post">-->
                       @using (Html.BeginForm("ChangeInfo", "BusinessUser", FormMethod.Post, new { name = "f_register" }))
                       {
                        <table class="register-form" border="0" cellpadding="0" cellspacing="0">
                            <tr>
                                <td class="form-title" colspan="2">
                                    Sửa thông tin cá nhân
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Tên doanh nghiệp:<br />
                                    <!--<input type="text" class="textbox" name="register_fullname" />-->                                    
                                    @Html.TextBoxFor(model => model.Ten, new { @class = "textbox", name = "register_fullname" })
                                </td>                                
                            </tr>
                            <tr>
                                <td>
                                    Mô tả:<br />
                                    <!--<input type="text" class="textbox" name="register_email" />-->
                                    @Html.TextBoxFor(model => model.MoTa, new { @class = "textbox", name = "register_email" })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Lĩnh vực kinh doanh:<br />
                                    <!--<input type="text" class="textbox" name="register_email" />-->
                                    @Html.TextBoxFor(model => model.NgheNghiep, new { @class = "textbox", name = "register_email" })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Địa chỉ:<br />
                                    <!--<input type="text" class="textbox" name="register_email" />-->
                                    @Html.TextBoxFor(model => model.DiaChi, new { @class = "textbox", name = "register_email" })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Điện thoại:<br />
                                    <!--<input type="text" class="textbox" name="register_pwd" />-->
                                    @Html.TextBoxFor(model => model.DienThoai, new { @class = "textbox", name = "register_pwd" })
                                   
                                </td>                                 
                                @if (ViewBag.changeInfo != null && (bool)ViewBag.changeInfo == true)
                                {
                                    <h1 class="status_err"> Thay đổi thông tin thất bại!</h1>
                                }  
                            </tr>
                             

                            @*Loại người dùng<~~*@
                           
                            <tr>
                                <td align="center" colspan="2">
                                    <input type="submit" class="button" name="register_submit" value="Thay đổi" />
                                </td>
                            </tr>
                        </table>
                       }<!--</form>-->
                    </div>

Source/MXHDL_DiMuonNoi/Views/BusinessUser/Header.cshtml
@model DTOLibrary.THONGTINDOANHNGHIEP
@{
    Layout = "~/Views/Shared/_EmptyLayout.cshtml";
    bool isOwner = false;
    if (ViewBag.isOwner != null)
    {
        isOwner = ViewBag.isOwner;
    }
}
<div id="box-popup-changeavt" class="grid_18 box-popup">
    <div class="box-titlebar" onclick="$('#box-popup-changeavt').toggle();">
        [X] Đóng</div>
    <div class="box-content">
        Upload avatar mới:</div>
    @using (@Html.BeginForm("ChangeAvatar", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {                 
        <input type="file" value="Chọn hình" name="file" />
        <input type="submit" value="OK" />                                  
    }
</div>
<div id="box-popup-changecvr" class="grid_18 box-popup">
    <div class="box-titlebar" onclick="$('#box-popup-changecvr').toggle();">
        [X] Đóng</div>
    <div class="box-content">
        Upload cover mới:</div>
    @using (@Html.BeginForm("ChangeCover", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {                 
        <input type="file" value="Chọn hình" name="file" />
        <input type="submit" value="OK" />                                  
    }
</div>
<div class="wrapper" style="border-top: 0;">
    <!-- header -->
    <div class="header">
        @if (isOwner)
        {		
            <!-- user photo -->
            <div class="push_1 grid_4 user-photo" onmouseover="$('#btn_changeAvatar').toggle();"
                onmouseout="$('#btn_changeAvatar').toggle();">
                <div class="user-box-border">
                    <img src="@Url.Content("~/" + Model.AnhDaiDien)"/>
                </div>
                <div id="btn_changeAvatar" class="btn-popup-changeavt" onclick="$('#box-popup-changeavt').toggle();">
                    Đổi hình đại diện</div>
            </div>
        }
        else
        {
            <div class="push_1 grid_4 user-photo">
                <div class="user-box-border">
                    <img src="@Url.Content("~/" + Model.AnhDaiDien)"/>
                </div>
                <div id="btn_changeAvatar" class="btn-popup-changeavt" onclick="$('#box-popup-changeavt').toggle();">
                    Đổi hình đại diện</div>
            </div>
			
        }
        <!-- user info -->
        <div class="push_1 grid_18 user-info">
            <div class="user-box-border">
                <table class="user-info-text">
                    <tr>
                        <td valign="top" align="left" width="400px">
                            <div class="user-name">@Model.Ten</div>
                            <div class="user-job">@Model.NgheNghiep</div>
                        </td>
                        <td valign="top" align="right">
                            Hiện đang ở @Model.DiaChi
                        </td>
                    </tr>
                    <tr>                        
                        <td valign="bottom" align="right">
                            "@Model.TamTrang"
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <!-- friends toolbox 
3/5/2013 chua add
-->
    @if (!isOwner)
    {

        String friendState = (String)ViewBag.FriendState;
        if (!friendState.Equals("ChuaDangNhap"))
        {
            String btnText = "Kết bạn";
            if (friendState.Equals("BanBe"))
            {
                btnText = "Đã kết bạn";
            }
            else if (friendState.Equals("ChoDongY"))
            {
                btnText = "Xác nhận bạn bè";
            }
            else if (friendState.Equals("DaYeuCau"))
            {
                btnText = "Đã gửi yêu cầu";
            }
                
        <div class="friends-toolbox">
            <div class="push_15 grid_9 tools">
                <a href="/Friend/AddFriend/@ViewBag.email">
                    <input type="button" class="btn-tool" value="@btnText" />
                </a>
                <!--<input type="button" class="btn-tool" value="Bạn bè" />-->
                <input type="button" class="btn-tool" value="Nhắn tin" />
            </div>
        </div>
        }
    }
    else
    {	
        <!-- search box -->
        <div class="search-box">
            <div class="push_14 grid_9 search-content">
                <form method="post" action="timkiem.html" onsubmit="alert('Demo: tìm kiếm địa điểm \'Tây Ninh\'');">
                <input type="text" class="search-input" value="Điểm đến tiếp theo của bạn?.." onfocus="if(this.value=='Điểm đến tiếp theo của bạn?..')this.value='';"
                    onblur="if(this.value=='')this.value='Điểm đến tiếp theo của bạn?..';" />
                <div class="search-icon">
                    <input type="submit" class="search-button" value="" />
                </div>
                </form>
            </div>
        </div>
    }
    <!-- cover -->
    @if (isOwner)
    {
        <div class="clear">
        </div>
        <div onmouseover="$('#btn_changeCover').toggle();" onmouseout="$('#btn_changeCover').toggle();">
            <div class="grid_24 cover">
                <img src="@Url.Content("~/" + Model.AnhBia)" />
            </div>
            <div id="btn_changeCover" class="btn-popup-changecvr" onclick="$('#box-popup-changecvr').toggle();">
                Đổi hình nền</div>
        </div>		
    }
    else
    {
        <div class="grid_24 cover">
            <img src="@Url.Content("~/" + Model.AnhBia)" />
        </div>
    }
    <div class="clear">
    </div>

Source/MXHDL_DiMuonNoi/Views/BusinessUser/Toolbar.cshtml
@{
    Layout = "~/Views/Shared/_EmptyLayout.cshtml";
    bool isOwner = false;
    if (ViewBag.isOwner != null)
    {
        isOwner = ViewBag.isOwner;
    }
}

 <div class="nav" style="padding: 10px 5px 0px 0px">
    <!-- status form -->
    @if (isOwner)
    {
    <div class="grid_8 statusForm">
        <form method="post" name="statusForm">
        <div class="txt-status">
            <textarea class="txtStatus">Nhập thông điệp của bạn</textarea></div>
        <div class="btn-photo">
            <input type="button" class="btnPhoto" value="+ Thêm ảnh" /></div>
        <div class="btn-submit">
            <input type="button" class="btnSubmit" value="Gửi" /></div>
        </form>
    </div>
    }
    else
    {
        
    }   
    <!-- nav buttons -->
    <!-- nav buttons -->			
	<div class="grid_3 nav-button"><a href="/Post/New"><img src="../../../Content/images/icon/doanhnghiep/baiviet.png" /></a></div>
	<div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');"><img src="../../../Content/images/icon/doanhnghiep/hinhanh.png" /></a></div>
	<div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');"><img src="../../../Content/images/icon/doanhnghiep/khuyenmai.png" /></a></div>						
@*
    <div class="grid_3 nav-button">
        <a href="javascript:alert('Chức năng đang xây dựng');">
            <img src="../../../Content/images/icon/canhan/hinhanh.png" /></a></div>
    <div class="grid_3 nav-button">
        <a href="/Post/New">
            <img src="../../../Content/images/icon/canhan/baiviet.png" /></a></div>
    <div class="grid_3 nav-button">
        <a href="javascript:alert('Chức năng đang xây dựng');">
            <img src="../../../Content/images/icon/canhan/chuyendi.png" /></a></div>
    <div class="grid_3 nav-button">
        <a href="javascript:alert('Chức năng đang xây dựng');">
            <img src="../../../Content/images/icon/canhan/yeuthich.png" /></a></div>
    <div class="grid_3 nav-button">
        <a href="/Friend/Index">
            <img src="../../../Content/images/icon/canhan/banbe.png" /></a></div>*@
    <div class="clear">
    </div>
    </div>
       