Source/MXHDL_DiMuonNoi/Models/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MXHDL_DiMuonNoi.Models
{
    public class Search
    {
        [Display(Name = "Từ khóa")]
        public string Keyword { set; get; }
        [Display(Name = "Tùy chọn tìm kiếm")]
        public string SearchOpt { set; get; }
        

        public Search()
        {
            this.Keyword = "";
            this.SearchOpt = "All";
        }
    }
}

Source/MXHDL_DiMuonNoi/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTOLibrary;

namespace MXHDL_DiMuonNoi.Controllers
{
    public class PostController : Controller
    {
        //
        // GET: /Post/
        BUSLibrary.SubmittedPost busRes = new BUSLibrary.SubmittedPost();
        BUSLibrary.RetrievedPost busRes2 = new BUSLibrary.RetrievedPost();
        
        BUSLibrary.Account busAccount = new BUSLibrary.Account();
        public ActionResult Index(String id)
        {
            String email = "";
            var cookie = Request.Cookies["Email"];

            if (cookie == null)
            {
                return View("Login");
            }

            email = cookie.Value;
            DTOLibrary.THONGTIN accInfos = ( DTOLibrary.THONGTIN)busAccount.getAccountInfos(email);

            ViewBag.AccInfos = accInfos;
            DTOLibrary.BaiViet post = busRes2.getPost(int.Parse(id));
            return View(post);
        }
        public ActionResult New()
        {
            String email = "";
            var cookie = Request.Cookies["Email"];

            if (cookie == null)
            {
                return View("Login");
            }

            email = cookie.Value;
            DTOLibrary.THONGTIN accInfos = (DTOLibrary.THONGTIN)busAccount.getAccountInfos(email);

            ViewBag.AccInfos = accInfos;
            return View();
        }
        [HttpPost]
        public ActionResult New(SubmittedPost model)
        {
            String email = "";
            var cookie = Request.Cookies["Email"];

            if (cookie == null)
            {
                return View("Login");
            }

            email = cookie.Value;
            model.Type = busAccount.getUserType(email);
            model.Email = email;
            bool result = busRes.submitUserPost(email, model);
            return Redirect("/Account/Home");
        }

        
    }
}

Source/MXHDL_DiMuonNoi/Controllers/SearchController.cs
using MXHDL_DiMuonNoi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MXHDL_DiMuonNoi.Controllers
{
    public class SearchController : Controller
    {
        //
        // GET: /Search/
        BUSLibrary.RetrievedPost busRes = new BUSLibrary.RetrievedPost();
        BUSLibrary.Account busAccount = new BUSLibrary.Account();
        public ActionResult Index()
        {
            String email = "";
            var cookie = Request.Cookies["Email"];

            if (cookie == null)
            {
                return View("Login");
            }

            email = cookie.Value;
            DTOLibrary.THONGTIN accInfos = (DTOLibrary.THONGTIN)busAccount.getAccountInfos(email);

            ViewBag.AccInfos = accInfos;
            return View();
        }

        public ActionResult Search(Search model)
        {
            String email = "";
            var cookie = Request.Cookies["Email"];

            if (cookie == null)
            {
                return View("Login");
            }

            email = cookie.Value;
            DTOLibrary.THONGTIN accInfos = (DTOLibrary.THONGTIN)busAccount.getAccountInfos(email);

            ViewBag.AccInfos = accInfos;

            List<DTOLibrary.RetrievedPost> userPosts = busRes.getUserPosts(model.Keyword);
            List<DTOLibrary.RetrievedPost> systemPosts = busRes.getSystemPosts(model.Keyword);
            if (model.SearchOpt == "UserPost")
            {
                systemPosts.Clear();
            }
            if (model.SearchOpt == "SystemPost")
            {
                userPosts.Clear();
            }
            ViewBag.UserPosts = userPosts;
            ViewBag.SystemPosts = systemPosts;
            return View(model);
        }
    }
}

Source/MXHDL_DiMuonNoi/Views/Search/Index.cshtml
@model MXHDL_DiMuonNoi.Models.Search

@{
    DTOLibrary.THONGTINCANHAN accInfos = ViewBag.AccInfos;
    ViewBag.Title = accInfos.Ten + " - DiMuonNoi";
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<title>@accInfos.Ten - DiMuonNoi</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="@Url.Content("~/Content/960_24_col.css")" 
                   rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/style.css")" 
                   rel="stylesheet" type="text/css" />
</head>
<body>

<!-- HEADER & NAVIGATION -->
<div class="container_24">
	      <!-- popup box for uploading new avatar/cover photo -->
	    <div id="box-popup-changeavt" class="grid_18 box-popup">
		    <div class="box-titlebar" onClick="$('#box-popup-changeavt').toggle();">[X] Đóng</div>
		    <div class="box-content">Upload avatar mới:</div>
             @using (@Html.BeginForm("ChangeAvatar", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }))
             {                 
                <input type="file" value="Chọn hình" name="file"/>
                <input type="submit" value="OK"/>                                  
             }
	    </div>
	    <div id="box-popup-changecvr" class="grid_18 box-popup">
		    <div class="box-titlebar" onClick="$('#box-popup-changecvr').toggle();">[X] Đóng</div>
		    <div class="box-content">Upload cover mới:</div>
             @using (@Html.BeginForm("ChangeCover", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }))
             {                 
                <input type="file" value="Chọn hình" name="file"/>
                <input type="submit" value="OK"/>                                  
             }
	    </div>
	<!-- left column (logo, menu) -->
	<div class="left-col">
		<!-- logo -->	
		<div class="logo"></div>
		<!-- menu -->
		<div class="menu">
        
		@Html.ActionLink("Trang cá nhân", "Home", "Account", new object { }, new { @class = "item"})
		<a class="item" href="javascript:alert('Chức năng đang xây dựng');">Sửa thông tin</a>
		<a class="item" href="javascript:alert('Chức năng đang xây dựng');">Đăng xuất</a>
        
		</div>
	</div>
	
	<!-- column column (advertisements) -->
	<div class="right-col">	
		<div class="grid_4 promotions">Khuyến mãi</div>
		<!-- Ads -->
		<div class="grid_4 ad-box" >
		<div class="ad-box-content" >
			<img src="../../images/company/newworldhotel/albums/newroom/2.jpg"  /><br />
			New Rooms!<br />
			at <a class="link" href="doanhnghiep.html">New World's Hotel</a>
		</div>	
		</div>
		<div class="grid_4 ad-box" >
		<div class="ad-box-content" >
			<img src="../../../Content/images/company/newworldhotel/photos/pool.jpg"  /><br />
			Da Pool~!<br />
			New World's Hotel
		</div>	
		</div>
		<div class="grid_4 ad-box" >
		<div class="ad-box-content" >
			<img src="../../../Content/images/company/newworldhotel/albums/newroom/1.jpg"  /><br />
			New Promotion
		</div>	
		</div>
		<div class="grid_4 ad-box" >
		<div class="ad-box-content" >
			<img src="../../../Content/images/company/newworldhotel/albums/newroom/3.jpg"  /><br />
			Old Promotion
		</div>	
		</div>
	</div>

	<div class="wrapper" style="border-top: 0;" >
		<!-- header -->
		<div class="header" >
			<!-- user photo -->  
           @* <div class="push_1 grid_4 user-photo" onMouseOver="$('#btn_changeAvatar').toggle();" onMouseOut="$('#btn_changeAvatar').toggle();">
			<div class="user-box-border">
				<img src="@Url.Content("~/" + accInfos.AnhDaiDien)"/>
			</div>
			<div id="btn_changeAvatar" class="btn-popup-changeavt" onClick="$('#box-popup-changeavt').toggle();">
             @using (@Html.BeginForm("ChangeAvatar", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }))
             {
                 ViewBag.curHompageInfos = Model;
                 ViewBag.blah = "asdasdasdsad";
                <input type="file" value="Đổi hình đại diện" name="file"/>
                 <input type="submit" value="OK"/>
             }
            </div>			
			</div>    *@       
            <!-- user photo -->
			<div class="push_1 grid_4 user-photo" onMouseOver="$('#btn_changeAvatar').toggle();" onMouseOut="$('#btn_changeAvatar').toggle();">
			<div class="user-box-border">
				<img src="@Url.Content("~/" + accInfos.AnhDaiDien)"/>
			</div>
			<div id="btn_changeAvatar" class="btn-popup-changeavt" onClick="$('#box-popup-changeavt').toggle();">Đổi hình đại diện</div>			
			</div>
			
            
            
			<!-- user info -->
			<div class="push_1 grid_18 user-info" >
			<div class="user-box-border" >
				<table class="user-info-text">
					<tr>
						<td valign="top" align="left" width="400px">
							<div class="user-name">@accInfos.Ten</div>
							<div class="user-job">@accInfos.NgheNghiep</div>
						</td>
						<td valign="top" align="right">Hiện đang ở @accInfos.DiaChi</td>
					</tr>
					<tr>
						<td valign="bottom" align="left">Đã đặt chân đến 5 miền đất nước.</td>
						<td valign="bottom" align="right">"@accInfos.TamTrang"</td>
					</tr>
				</table>		
			</div>
			</div>			
		</div>
		<!-- search box -->
		<div class="search-box" >			
			<div class="push_14 grid_9 search-content">
				<form method="post" action="timkiem.html" onSubmit="alert('Demo: tìm kiếm địa điểm \'Tây Ninh\'');" >
					<input type="text" class="search-input" value="Điểm đến tiếp theo của bạn?.." onFocus="if(this.value=='Điểm đến tiếp theo của bạn?..')this.value='';" onBlur="if(this.value=='')this.value='Điểm đến tiếp theo của bạn?..';" />
					<div class="search-icon">
					<input type="submit" class="search-button" value="" />
					</div>
				</form>
			</div>			
		</div>		
        <!-- cover -->
		<div class="clear"></div>
		<div  onMouseOver="$('#btn_changeCover').toggle();" onMouseOut="$('#btn_changeCover').toggle();">
		<div class="grid_24 cover">
			<img src="@Url.Content("~/" + accInfos.AnhBia)" />		
		</div>
		<div id="btn_changeCover" class="btn-popup-changecvr" onClick="$('#box-popup-changecvr').toggle();">Đổi hình nền</div>
		</div>		

		<div class="clear"></div>
		<!-- navigator -->
		<div class="nav" style="padding: 10px 5px 0px 0px">
			<!-- status form -->
			<div class="grid_8 statusForm" >
				<form method="post" name="statusForm">
					<div class="txt-status"><textarea class="txtStatus" >Nhập thông điệp của bạn</textarea></div>
					<div class="btn-photo"><input type="button" class="btnPhoto" value="+ Thêm ảnh" /></div>
					<div class="btn-submit"><input type="button" class="btnSubmit" value="Gửi" /></div>
				</form>
			</div>
			<!-- nav buttons -->
			<div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');"><img src="../../../Content/images/icon/canhan/hinhanh.png" /></a></div>
			<div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');"><img src="../../../Content/images/icon/canhan/baiviet.png" /></a></div>
			<div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');"><img src="../../../Content/images/icon/canhan/chuyendi.png" /></a></div>
			<div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');"><img src="../../../Content/images/icon/canhan/yeuthich.png" /></a></div>
			<div class="grid_3 nav-button"><a href="javascript:alert('Chức năng đang xây dựng');"><img src="../../../Content/images/icon/canhan/banbe.png" /></a></div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<!-- END HEADER & NAVIGATION -->
<div class="clear"></div>

<!-- SINGLE POST : ALBUM -->
<div class="container_24 user-post-item">
	<div class="wrapper" >
		<table>
			<tr>
				<td valign="top" align="left">
					<div class="album-title">Tìm kiếm</div>
				</td>
			</tr>
            <tr>
                <td>
                    @using (Html.BeginForm("Search", "Search", FormMethod.Get)) 
                    {
                        @Html.LabelFor(Model => Model.Keyword)
                        @Html.TextBoxFor(Model => Model.Keyword)
                        <br />
                        <label>Tất cả</label>
                        @Html.RadioButtonFor(Model => Model.SearchOpt, "All", new {Checked = "true"})
                        <br />
                        <label>Trong bài viết thường</label>
                        @Html.RadioButtonFor(Model => Model.SearchOpt, "UserPost")
                        <br />
                        <label>Trong bài viết hệ thống</label>
                        @Html.RadioButtonFor(Model => Model.SearchOpt, "SystemPost")
                        <br />
                        <input type="submit" value="Tìm" />
                    }
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="container_24 user-post-item">
<div class="footer">
	<hr />
	<div class="footer-copyright">
	Bản quyền thuộc DiMuonNoi
	</div>
	<div class="footer-links">
		<a href="javascript:alert('Chức năng đang xây dựng');">Giới thiệu</a>
		<a href="javascript:alert('Chức năng đang xây dựng');">Trợ giúp</a>
		<a href="javascript:alert('Chức năng đang xây dựng');">Quy định</a>
		<a href="javascript:alert('Chức năng đang xây dựng');">Báo cáo</a>		
	</div>
</div></div>

</body>
</html>

Source/MXHDL_DiMuonNoi/Views/Search/Search.cshtml
@using DTOLibrary;
@{
    DTOLibrary.THONGTINCANHAN accInfos = ViewBag.AccInfos;
    ViewBag.Title = accInfos.Ten + " - DiMuonNoi";
    List<RetrievedPost> UserPosts = ViewBag.UserPosts;
    List<RetrievedPost> SystemPosts = ViewBag.SystemPosts;
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<title>Nguyễn Cường Thịnh - DiMuonNoi</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="@Url.Content("~/Content/960_24_col.css")" 
                   rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/style.css")" 
                   rel="stylesheet" type="text/css" />
</head>
<body>

<!-- HEADER & NAVIGATION -->
<div class="container_24">
	
	<!-- left column (logo, menu) -->
	<div class="left-col">
		<!-- logo -->	
		<div class="logo"></div>
		<!-- menu -->
		<div class="menu">
        
        @Html.ActionLink("Trang cá nhân", "Home", "Account", new object { }, new { @class = "item"})
		<a class="item" href="javascript:alert('Chức năng đang xây dựng');">Sửa thông tin</a>
		<a class="item" href="javascript:alert('Chức năng đang xây dựng');">Đăng xuất</a>
        
		</div>
	</div>
	
	<!-- column column (advertisements) -->
	<div class="right-col">	
		<div class="grid_4 promotions">Khuyến mãi</div>
		<!-- Ads -->
		<div class="grid_4 ad-box" >
		<div class="ad-box-content" >
			<img src="../../Content/images/company/newworldhotel/albums/newroom/2.jpg"  /><br />
			New Rooms!<br />
			at <a class="link" href="doanhnghiep.html">New World's Hotel</a>
		</div>	
		</div>
		<div class="grid_4 ad-box" >
		<div class="ad-box-content" >
			<img src="../../../Content/images/company/newworldhotel/photos/pool.jpg"  /><br />
			Da Pool~!<br />
			New World's Hotel
		</div>	
		</div>
		<div class="grid_4 ad-box" >
		<div class="ad-box-content" >
			<img src="../../../Content/images/company/newworldhotel/albums/newroom/1.jpg"  /><br />
			New Promotion
		</div>	
		</div>
		<div class="grid_4 ad-box" >
		<div class="ad-box-content" >
			<img src="../../../Content/images/company/newworldhotel/albums/newroom/3.jpg"  /><br />
			Old Promotion
		</div>	
		</div>
	</div>
<div class="wrapper" style="border-top: 0;" >
		<!-- search heading -->
		<div class="nav" style="padding: 10px 5px 0px 13px">
			<span class="search-heading">Tìm kiếm </span><span class="place-to-search">"@Model.Keyword"</span>
			<div class="clear"></div>
		</div>
	</div>
</div>
<!-- END HEADER & SEARCH HEADING -->
<div class="clear"></div>

<!-- PLACE DESCRIPTION -->

<div class="container_24 user-post-item">
	<div class="wrapper" >
		<table>
			<tr>
                <td valign="top" align="left">
                    @if (SystemPosts.Count != 0)
                    {
                        foreach (RetrievedPost p in SystemPosts)
                        {
                            <div class ="related-post">
					        <div class="place-title">@p.Title
						        <button class="like-btn">Yêu thích</button><button class="create-trip-btn">Lập chuyến đi</button>
					        </div>
					        <div class="clear"></div>
					        <div class="place-detail">@p.Content.</div>
                            </div>				
                        } 
                    }
                    else
                    {
                        <div class="place-title">Không tìm thấy thông tin từ hệ thống với từ khóa <span class="place-to-search">"@Model.Keyword"</span> </div>	
                    }
                </td>
			</tr>
		</table>
	</div>
</div>
<!-- END PLACE DESCRIPTION -->

@if (UserPosts != null)
{
<!-- RELATED POSTS AND ALBUMS -->
<div class="container_24 user-post-item">
	<div class="wrapper" >
		<table>
			<tr>
				<td valign="top" align="left">
					<div class="related-info-title">Thông tin liên quan</div>
				</td>
			</tr>
			<tr>
				<td>
                    @if (UserPosts.Count != 0)
                    {
                        foreach (RetrievedPost p in UserPosts)
                        {
                            <div class="related-post">
						        <table>
							        <tr>
								        <td valign="top" align="left" width="130px">
									        <div class="user-avatar" >
										        <img src="@Url.Content("~/UserDatas/Images/" + p.AvatarUrl + ".jpg")"  />
									        </div>	
								        </td>
								        <td valign="top" align="left">
									        <div class="related-post-title">@Html.ActionLink("Bài viết: " + @p.Title, "Index", "Post", new { Id = @p.Id }, new { }) <span class="post-author">bởi @p.Name </span></div>
									        <div class="related-post-detail">
										        @Html.Raw(System.Web.HttpUtility.HtmlDecode(p.Content))
									        </div>					
								        </td>
							        </tr>
						        </table>
					        </div>
                        }
                    }
                    else
                    {
                        <div class="place-title">Không tìm thấy bài viết từ khóa <span class="place-to-search">"@Model.Keyword"</span> </div>	
                    }
				</td>	
			</tr>
		</table>
	</div>
</div>
}
<!-- END RELATED POSTS AND ALBUMS -->


<div class="container_24 user-post-item">
<div class="footer">
	<hr />
	<div class="footer-copyright">
	Bản quyền thuộc DiMuonNoi
	</div>
	<div class="footer-links">
		<a href="javascript:alert('Chức năng đang xây dựng');">Giới thiệu</a>
		<a href="javascript:alert('Chức năng đang xây dựng');">Trợ giúp</a>
		<a href="javascript:alert('Chức năng đang xây dựng');">Quy định</a>
		<a href="javascript:alert('Chức năng đang xây dựng');">Báo cáo</a>		
	</div>
</div></div>

</body>
</html>